version: "3.1"
services:
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_PASSWORD: null
      MYSQL_ROOT_PASSWORD: null
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: supplies_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql
  app:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    restart: always
    links:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_DB: supplies_db
      MYSQL_PASSWORD: null
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
volumes:
  mysql_data:
